---

- name: install software requirements
  apt:
    name: "{{ movidius_debs }}"
    state: latest
  become: true

- name: create directory to store movidius software
  file:
    path: "{{ movidius_sdk_dir }}"
    state: directory
    mode: '0755'

- name: clone movidius sdk git repository
  git:
    repo: "{{ movidius_github_repo }}"
    dest: "{{ movidius_sdk_dir }}"

- name: clone movidius examples git repository
  git:
    repo: "{{ movidius_examples_github_repo }}"
    dest: "{{ movidius_examples_dir }}"
    
- name: configure virtual env
  lineinfile:
    path: "{{ movidius_sdk_dir }}/ncsdk.conf"
    line: "USE_VIRTUALENV=yes"
    state: present
