---

- name: update all packages
  apt:
    name: "*"
    state: latest
  become: yes

- name: install packages
  apt:
    name: "{{ ubuntu_pkgs }}"
  become: yes

- name: install gui
  command: /usr/bin/tasksel install ubuntu-desktop
  become: yes
